services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    image: llm-eng
    working_dir: /app
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    env_file:
      - .env
    models:
      - smollm2
models:
  smollm2:
    model: ai/smollm2:latest

